#!/usr/bin/env sh

if [[ -e ./setup.py ]]; then
	
	if [[ "$1" == "clean" ]]; then
		if [[ -e ./installed_files.txt ]]; then
			cat ./installed_files.txt | xargs rm -rf
		fi
		rm -rdf ./pyconfig.egg-info
		rm -rdf ./build
		rm -rdf ./dist
		find pyconfig -name "*.pyc" | xargs  rm -rf
	fi
	
	if [[ "$1" == "build" ]]; then
		if [[ "$2" == "3" ]]; then
			python3 ./setup.py install --record ./installed_files.txt
		else
			python ./setup.py install --user --record ./installed_files.txt
		fi
	fi
	
	if [[ "$1" == "clean" ]] && [[ "$2" == "build" ]]; then
		if [[ "$3" == "3" ]]; then
			python3 ./setup.py install --record ./installed_files.txt
		else
			python ./setup.py install --user --record ./installed_files.txt
		fi
	fi
else
	echo "Please run this script from the directory it is in!"
fi