#!/usr/bin/python

try:
	import os
	import subprocess
	def make_call(call_args):
		error = 0
		output = ''
		try:
			output = subprocess.check_output(call_args)
			error = 0
		except subprocess.CalledProcessError as e:
			output = e.output
			error = e.returncode
		return output

	install_path = os.path.abspath(os.path.dirname(__file__))
	os.chdir(install_path)
	commit_hash = make_call(('git', 'rev-parse', '--short', 'HEAD')).decode('utf-8').strip('\n')
	remote_origin = make_call(('git', 'ls-remote', '--get-url')).decode('utf-8').strip('\n')
	if len(commit_hash) > 0 and len(remote_origin) > 0:
		versions_path = os.path.join(install_path, 'pyconfig/version.py')
		fd = open(versions_path, 'w')
		fd.write('__version__ = "'+module_version+' ('+remote_origin+' @ '+commit_hash+')"')
		fd.close()
except ImportError as e:
	raise e