#!/usr/bin/env bash
git_path=`git rev-parse --show-toplevel`
pushd $git_path

commit_hash=`git rev-parse --short HEAD`
remote_origin=`git ls-remote --get-url`
echo "remote_origin = '$remote_origin'" > ./pyconfig/version_info.py
echo "commit_hash = '$commit_hash'" >> ./pyconfig/version_info.py
git add ./pyconfig/version_info.py

popd
