# Copyright (c) 2016-2020, Samantha Marshall (http://pewpewthespells.com)
# All rights reserved.
#
# https://github.com/samdmarshall/pyconfig
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.
#
# 3. Neither the name of Samantha Marshall nor the names of its contributors may
# be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.

# this file contains a list of all of the build settings (by name) that are
## registered as "built-ins" to any Xcode project. These will be present no
## matter how a particular target will be configured. These definitions are
## used as part of the analysis engine to exclude these from the pool of
## undefined variables.
BuiltinLookupTable = [
    #
    'ADDITIONAL_SDKS',
    'ARCHS',
    'ONLY_ACTIVE_ARCH',
    'SDKROOT',
    'SUPPORTED_PLATFORMS',
    'VALID_ARCHS',

    #
    'BUILD_DIR',
    'EFFECTIVE_PLATFORM_NAME',
    'CONFIGURATION_BUILD_DIR',
    'CONFIGURATION_TEMP_DIR',
    'OBJROOT',
    'SHARED_PRECOMPS_DIR',
    'SYMROOT',

    #
    'APPLICATION_EXTENSION_API_ONLY',
    'BUILD_VARIANTS',
    'DEBUG_INFORMATION_FORMAT',
    'EMBEDDED_CONTENT_CONTAINS_SWIFT',
    'GCC_VERSION',
    'GENERATE_PROFILING_CODE',
    'PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR',
    'SCAN_ALL_SOURCE_FILES_FOR_INCLUDES',
    'VALIDATE_PRODUCT',

    #
    'CODE_SIGN_ENTITLEMENTS',
    'CODE_SIGN_IDENTITY',
    'CODE_SIGN_RESOURCE_RULES_PATH',
    'OTHER_CODE_SIGN_FLAGS',
    'PROVISIONING_PROFILE',
    'EMBEDDED_PROFILE_NAME=',

    #
    'ALTERNATE_GROUP',
    'ALTERNATE_MODE',
    'ALTERNATE_OWNER',
    'ALTERNATE_PERMISSIONS_FILES',
    'COMBINE_HIDPI_IMAGES',
    'COPY_PHASE_STRIP',
    'DEPLOYMENT_LOCATION',
    'DEPLOYMENT_POSTPROCESSING',
    'DSTROOT',
    'INSTALL_GROUP',
    'INSTALL_MODE_FLAG',
    'INSTALL_OWNER',
    'INSTALL_PATH',
    'PRODUCT_DEFINITION_PLIST',
    'SEPARATE_STRIP',
    'SKIP_INSTALL',
    'STRIPFLAGS',
    'STRIP_INSTALLED_PRODUCT',
    'STRIP_STYLE',

    #
    'MODULE_NAME',
    'MODULE_START',
    'MODULE_STOP',
    'MODULE_VERSION',

    #
    'BUNDLE_LOADER',
    'DEAD_CODE_STRIPPING',
    'DYLIB_COMPATIBILITY_VERSION',
    'DYLIB_CURRENT_VERSION',
    'DYLIB_INSTALL_NAME_BASE',
    'EXPORTED_SYMBOLS_FILE',
    'GENERATE_MASTER_OBJECT_FILE',
    'INIT_ROUTINE',
    'KEEP_PRIVATE_EXTERNS',
    'LD_DEPENDENCY_INFO_FILE',
    'LD_DYLIB_INSTALL_NAME',
    'LD_GENERATE_MAP_FILE',
    'LD_MAP_FILE_PATH',
    'LD_NO_PIE',
    'LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER',
    'LD_RUNPATH_SEARCH_PATHS',
    'LINKER_DISPLAYS_MANGLED_NAMES',
    'LINK_WITH_STANDARD_LIBRARIES',
    'MACH_O_TYPE',
    'ORDER_FILE',
    'OTHER_LDFLAGS',
    'OTHER_LIBTOOLFLAGS',
    'PRELINK_FLAGS',
    'PRELINK_LIBS',
    'PRESERVE_DEAD_CODE_INITS_AND_TERMS',
    'SECTORDER_FLAGS',
    'SEPARATE_SYMBOL_EDIT',
    'UNEXPORTED_SYMBOLS_FILE',
    'WARNING_LDFLAGS',
    'ENABLE_BITCODE',
    'BITCODE_GENERATION_MODE',
    'CLANG_BITCODE_GENERATION_MODE',

    #
    'APPLY_RULES_IN_COPY_FILES',
    'COPYING_PRESERVES_HFS_DATA',
    'CREATE_INFOPLIST_SECTION_IN_BINARY',
    'DEFINES_MODULE',
    'EXECUTABLE_EXTENSION',
    'EXECUTABLE_PREFIX',
    'FRAMEWORK_VERSION',
    'GENERATE_PKGINFO_FILE',
    'INFOPLIST_EXPAND_BUILD_SETTINGS',
    'INFOPLIST_FILE',
    'INFOPLIST_OTHER_PREPROCESSOR_FLAGS',
    'INFOPLIST_OUTPUT_FORMAT',
    'INFOPLIST_PREFIX_HEADER',
    'INFOPLIST_PREPROCESS',
    'INFOPLIST_PREPROCESSOR_DEFINITIONS',
    'MODULEMAP_FILE',
    'MODULEMAP_PRIVATE_FILE',
    'PLIST_FILE_OUTPUT_FORMAT',
    'PRIVATE_HEADERS_FOLDER_PATH',
    'PRODUCT_MODULE_NAME',
    'PRODUCT_NAME',
    'PUBLIC_HEADERS_FOLDER_PATH',
    'STRINGS_FILE_OUTPUT_ENCODING',
    'WRAPPER_EXTENSION',

    #
    'ALWAYS_SEARCH_USER_PATHS',
    'EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES',
    'FRAMEWORK_SEARCH_PATHS',
    'HEADER_SEARCH_PATHS',
    'INCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES',
    'LIBRARY_SEARCH_PATHS',
    'REZ_SEARCH_PATHS',
    'USER_HEADER_SEARCH_PATHS',

    #
    'TEST_HOST',
    'TREAT_MISSING_BASELINES_AS_TEST_FAILURES',

    #
    'CURRENT_PROJECT_VERSION',
    'VERSIONING_SYSTEM',
    'VERSION_INFO_BUILDER',
    'VERSION_INFO_EXPORT_DECL',
    'VERSION_INFO_FILE',
    'VERSION_INFO_PREFIX',
    'VERSION_INFO_SUFFIX',

    #
    'CLANG_DEBUG_INFORMATION_LEVEL',
    'CLANG_OPTIMIZATION_PROFILE_FILE',
    'CLANG_USE_OPTIMIZATION_PROFILE',
    'CLANG_X86_VECTOR_INSTRUCTIONS',
    'GCC_DYNAMIC_NO_PIC',
    'GCC_ENABLE_KERNEL_DEVELOPMENT',
    'GCC_FAST_MATH',
    'GCC_GENERATE_DEBUGGING_SYMBOLS',
    'GCC_GENERATE_TEST_COVERAGE_FILES',
    'GCC_INLINES_ARE_PRIVATE_EXTERN',
    'GCC_INSTRUMENT_PROGRAM_FLOW_ARCS',
    'GCC_NO_COMMON_BLOCKS',
    'GCC_OPTIMIZATION_LEVEL',
    'GCC_REUSE_STRINGS',
    'GCC_STRICT_ALIASING',
    'GCC_SYMBOLS_PRIVATE_EXTERN',
    'GCC_THREADSAFE_STATICS',
    'GCC_UNROLL_LOOPS',
    'LLVM_LTO',

    #
    'OTHER_CFLAGS',
    'OTHER_CPLUSPLUSFLAGS',
    'WARNING_CFLAGS',

    #
    'GCC_CHAR_IS_UNSIGNED_CHAR',
    'GCC_CW_ASM_SYNTAX',
    'GCC_C_LANGUAGE_STANDARD',
    'GCC_ENABLE_ASM_KEYWORD',
    'GCC_ENABLE_BUILTIN_FUNCTIONS',
    'GCC_ENABLE_FLOATING_POINT_LIBRARY_CALLS',
    'GCC_ENABLE_PASCAL_STRINGS',
    'GCC_ENABLE_TRIGRAPHS',
    'GCC_INCREASE_PRECOMPILED_HEADER_SHARING',
    'GCC_INPUT_FILETYPE',
    'GCC_LINK_WITH_DYNAMIC_LIBRARIES',
    'GCC_PRECOMPILE_PREFIX_HEADER',
    'GCC_PREFIX_HEADER',
    'GCC_SHORT_ENUMS',
    'GCC_USE_STANDARD_INCLUDE_SEARCHING',

    #
    'CLANG_CXX_LANGUAGE_STANDARD',
    'CLANG_CXX_LIBRARY',
    'GCC_ENABLE_CPP_EXCEPTIONS',
    'GCC_ENABLE_CPP_RTTI',

    #
    'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES',
    'CLANG_ENABLE_MODULES',
    'CLANG_MODULES_AUTOLINK',

    #
    'CLANG_ENABLE_OBJC_ARC',
    'CLANG_LINK_OBJC_RUNTIME',
    'GCC_ENABLE_OBJC_EXCEPTIONS',

    #
    'ENABLE_NS_ASSERTIONS',
    'ENABLE_STRICT_OBJC_MSGSEND',
    'GCC_PREPROCESSOR_DEFINITIONS',
    'GCC_PREPROCESSOR_DEFINITIONS_NOT_USED_IN_PRECOMPS',

    #
    'GCC_TREAT_WARNINGS_AS_ERRORS',
    'GCC_WARN_INHIBIT_ALL_WARNINGS',
    'GCC_WARN_PEDANTIC',

    #
    'CLANG_WARN_ASSIGN_ENUM',
    'CLANG_WARN_BOOL_CONVERSION',
    'CLANG_WARN_CONSTANT_CONVERSION',
    'CLANG_WARN_DOCUMENTATION_COMMENTS',
    'CLANG_WARN_EMPTY_BODY',
    'CLANG_WARN_ENUM_CONVERSION',
    'CLANG_WARN_IMPLICIT_SIGN_CONVERSION',
    'CLANG_WARN_INT_CONVERSION',
    'CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION',
    'CLANG_WARN_UNREACHABLE_CODE',
    'GCC_TREAT_IMPLICIT_FUNCTION_DECLARATIONS_AS_ERRORS',
    'GCC_TREAT_INCOMPATIBLE_POINTER_TYPE_WARNINGS_AS_ERRORS',
    'GCC_WARN_64_TO_32_BIT_CONVERSION',
    'GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS',
    'GCC_WARN_ABOUT_MISSING_FIELD_INITIALIZERS',
    'GCC_WARN_ABOUT_MISSING_NEWLINE',
    'GCC_WARN_ABOUT_MISSING_PROTOTYPES',
    'GCC_WARN_ABOUT_POINTER_SIGNEDNESS',
    'GCC_WARN_ABOUT_RETURN_TYPE',
    'GCC_WARN_CHECK_SWITCH_STATEMENTS',
    'GCC_WARN_FOUR_CHARACTER_CONSTANTS',
    'GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED',
    'GCC_WARN_MISSING_PARENTHESES',
    'GCC_WARN_SHADOW',
    'GCC_WARN_SIGN_COMPARE',
    'GCC_WARN_TYPECHECK_CALLS_TO_PRINTF',
    'GCC_WARN_UNDECLARED_SELECTOR',
    'GCC_WARN_UNINITIALIZED_AUTOS',
    'GCC_WARN_UNKNOWN_PRAGMAS',
    'GCC_WARN_UNUSED_FUNCTION',
    'GCC_WARN_UNUSED_LABEL',
    'GCC_WARN_UNUSED_PARAMETER',
    'GCC_WARN_UNUSED_VALUE',
    'GCC_WARN_UNUSED_VARIABLE',

    #
    'CLANG_WARN_CXX0X_EXTENSIONS',
    'CLANG_WARN__EXIT_TIME_DESTRUCTORS',
    'GCC_WARN_ABOUT_INVALID_OFFSETOF_MACRO',
    'GCC_WARN_HIDDEN_VIRTUAL_FUNCTIONS',
    'GCC_WARN_NON_VIRTUAL_DESTRUCTOR',

    #
    'CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS',
    'CLANG_WARN_DIRECT_OBJC_ISA_USAGE',
    'CLANG_WARN_OBJC_IMPLICIT_ATOMIC_PROPERTIES',
    'CLANG_WARN_OBJC_MISSING_PROPERTY_SYNTHESIS',
    'CLANG_WARN_OBJC_ROOT_CLASS',
    'CLANG_WARN__DUPLICATE_METHOD_MATCH',
    'GCC_WARN_ALLOW_INCOMPLETE_PROTOCOL',
    'GCC_WARN_MULTIPLE_DEFINITION_TYPES_FOR_SELECTOR',
    'GCC_WARN_STRICT_SELECTOR_MATCH',
    'GCC_WARN_UNDECLARED_SELECTOR',

    #
    'CLANG_WARN_OBJC_EXPLICIT_OWNERSHIP_TYPE',
    'CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF',
    'CLANG_WARN_OBJC_RECEIVER_WEAK',
    'CLANG_WARN_OBJC_REPEATED_USE_OF_WEAK',
    'CLANG_WARN__ARC_BRIDGE_CAST_NONARC',

    #
    'ASSETCATALOG_COMPILER_APPICON_NAME',
    'ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME',
    'ASSETCATALOG_NOTICES',
    'ASSETCATALOG_OTHER_FLAGS',
    'ASSETCATALOG_WARNINGS',

    #
    'IBC_COMPILER_AUTO_ACTIVATE_CUSTOM_FONTS',
    'IBC_ERRORS',
    'IBC_FLATTEN_NIBS',
    'IBC_NOTICES',
    'IBC_OTHER_FLAGS',
    'IBC_WARNINGS',

    #
    'OSACOMPILE_EXECUTE_ONLY',
    'OTHER_OSACOMPILEFLAGS',

    #
    'CLANG_STATIC_ANALYZER_MODE',
    'CLANG_STATIC_ANALYZER_MODE_ON_ANALYZE_ACTION',
    'RUN_CLANG_STATIC_ANALYZER',

    #
    'CLANG_ANALYZER_DEADCODE_DEADSTORES',
    'CLANG_ANALYZER_GCD',
    'CLANG_ANALYZER_MEMORY_MANAGEMENT',

    #
    'CLANG_ANALYZER_OBJC_ATSYNC',
    'CLANG_ANALYZER_OBJC_COLLECTIONS',
    'CLANG_ANALYZER_OBJC_INCOMP_METHOD_TYPES',
    'CLANG_ANALYZER_OBJC_NSCFERROR',
    'CLANG_ANALYZER_OBJC_RETAIN_COUNT',
    'CLANG_ANALYZER_OBJC_SELF_INIT',
    'CLANG_ANALYZER_OBJC_UNUSED_IVARS',

    #
    'CLANG_ANALYZER_SECURITY_FLOATLOOPCOUNTER',
    'CLANG_ANALYZER_SECURITY_INSECUREAPI_GETPW_GETS',
    'CLANG_ANALYZER_SECURITY_INSECUREAPI_MKSTEMP',
    'CLANG_ANALYZER_SECURITY_INSECUREAPI_RAND',
    'CLANG_ANALYZER_SECURITY_INSECUREAPI_STRCPY',
    'CLANG_ANALYZER_SECURITY_INSECUREAPI_UNCHECKEDRETURN',
    'CLANG_ANALYZER_SECURITY_INSECUREAPI_VFORK',
    'CLANG_ANALYZER_SECURITY_KEYCHAIN_API',

    #
    'MTL_ENABLE_DEBUG_INFO',
]
