# Copyright (c) 2016, Samantha Marshall (http://pewpewthespells.com)
# All rights reserved.
#
# https://github.com/samdmarshall/pyconfig
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.
#
# 3. Neither the name of Samantha Marshall nor the names of its contributors may
# be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.

RuntimeLookupTable = [
    #
    'ALTERNATE_GROUP',
    'ALTERNATE_MODE',
    'ALTERNATE_OWNER',

    #
    'APPLE_INTERNAL_DEVELOPER_DIR',
    'APPLE_INTERNAL_DIR',
    'APPLE_INTERNAL_DOCUMENTATION_DIR',
    'APPLE_INTERNAL_LIBRARY_DIR',
    'APPLE_INTERNAL_TOOLS',

    #
    'ARCHS_STANDARD',
    'ARCHS_STANDARD_32_64_BIT',
    'ARCHS_STANDARD_32_BIT',
    'ARCHS_STANDARD_64_BIT',
    'ARCHS_STANDARD_INCLUDING_64_BIT',

    'ARCHS_STANDARD',
    'ARCHS_STANDARD_32_64_BIT',
    'ARCHS_STANDARD_32_BIT',
    'ARCHS_STANDARD_64_BIT',
    'ARCHS_STANDARD_INCLUDING_64_BIT',
    'ARCHS_UNIVERSAL_IPHONE_OS',

    #
    'BUILD_DIR',
    'BUILD_ROOT',
    'BUILD_STYLE',
    'BUILT_PRODUCTS_DIR',

    #
    'CACHE_ROOT',
    'COMPOSITE_SDK_DIRS',

    #
    'DEVELOPER_APPLICATIONS_DIR',
    'DEVELOPER_BIN_DIR',
    'DEVELOPER_FRAMEWORKS_DIR',
    'DEVELOPER_FRAMEWORKS_DIR_QUOTED',
    'DEVELOPER_LIBRARY_DIR',
    'DEVELOPER_SDK_DIR',
    'DEVELOPER_TOOLS_DIR',
    'DEVELOPER_USR_DIR',
    'LEGACY_DEVELOPER_DIR',

    #
    'COLOR_DIAGNOSTICS',

    #
    'EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS',

    #
    'FILE_LIST',

    #
    'GCC3_VERSION',

    #
    'HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT',
    'HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES',
    'HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS',
    'HEADERMAP_INCLUDES_PROJECT_HEADERS',
    'HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES',
    'HEADERMAP_USES_VFS',

    #
    'INSTALL_DIR',
    'INSTALL_ROOT',

    #
    'JAVAC_DEFAULT_FLAGS',
    'JAVA_APP_STUB',
    'JAVA_ARCHIVE_CLASSES',
    'JAVA_ARCHIVE_TYPE',
    'JAVA_COMPILER',
    'JAVA_FRAMEWORK_RESOURCES_DIRS',
    'JAVA_JAR_FLAGS',
    'JAVA_SOURCE_SUBDIR',
    'JAVA_USE_DEPENDENCIES',
    'JAVA_ZIP_FLAGS',

    #
    'LIBRARY_FLAG_NOSPACE',
    'LIBRARY_FLAG_PREFIX',
    'LIBRARY_KEXT_INSTALL_PATH',

    #
    'LOCAL_ADMIN_APPS_DIR',
    'LOCAL_APPS_DIR',
    'LOCAL_DEVELOPER_DIR',
    'LOCAL_LIBRARY_DIR',

    #
    'OBJC_ABI_VERSION',

    #
    'AVAILABLE_PLATFORMS',
    'OS',
    'PLATFORM_DEVELOPER_APPLICATIONS_DIR',
    'PLATFORM_DEVELOPER_BIN_DIR',
    'PLATFORM_DEVELOPER_LIBRARY_DIR',
    'PLATFORM_DEVELOPER_TOOLS_DIR',
    'PLATFORM_DEVELOPER_USR_DIR',

    #
    'PROJECT_DERIVED_FILE_DIR',
    'PROJECT_TEMP_DIR',
    'PROJECT_TEMP_ROOT',

    #
    'REMOVE_CVS_FROM_RESOURCES',
    'REMOVE_GIT_FROM_RESOURCES',
    'REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES',
    'REMOVE_HG_FROM_RESOURCES',
    'REMOVE_SVN_FROM_RESOURCES',

    #
    'SHARED_PRECOMPS_DIR',

    #
    'SYSTEM_ADMIN_APPS_DIR',
    'SYSTEM_APPS_DIR',
    'SYSTEM_CORE_SERVICES_DIR',
    'SYSTEM_DEMOS_DIR',
    'SYSTEM_DEVELOPER_APPS_DIR',
    'SYSTEM_DEVELOPER_BIN_DIR',
    'SYSTEM_DEVELOPER_DEMOS_DIR',
    'SYSTEM_DEVELOPER_DIR',
    'SYSTEM_DEVELOPER_DOC_DIR',
    'SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR',
    'SYSTEM_DEVELOPER_JAVA_TOOLS_DIR',
    'SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR',
    'SYSTEM_DEVELOPER_RELEASENOTES_DIR',
    'SYSTEM_DEVELOPER_TOOLS',
    'SYSTEM_DEVELOPER_TOOLS_DOC_DIR',
    'SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR',
    'SYSTEM_DEVELOPER_USR_DIR',
    'SYSTEM_DEVELOPER_UTILITIES_DIR',
    'SYSTEM_DOCUMENTATION_DIR',
    'SYSTEM_KEXT_INSTALL_PATH',
    'SYSTEM_LIBRARY_DIR',

    #
    'TARGET_TEMP_DIR',
    'TARGET_BUILD_DIR',

    #
    'TEMP_DIR',
    'TEMP_FILES_DIR',
    'TEMP_FILE_DIR',
    'TEMP_ROOT',

    #
    'CHMOD',
    'CHOWN',
    'CP',
    'ICONV',
    'LEX',
    'OSAC',
    'SED',
    'YACC',

    #
    'USER_APPS_DIR',
    'USER_LIBRARY_DIR',

    #
    'XCODE_APP_SUPPORT_DIR',
]
